name: forms814 # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '1.3.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: a tool for website developers on records collection # 79 char long summary
description: |
  a tool for website developers on records collection
  
  speeds up creating forms for your website. Needed when you have a lot of forms to create


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:
  armhf:
  
parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - go
    build-packages:
      - build-essential
      - gcc
      - libgl1-mesa-dev
      - xorg-dev
      - libc6-dev

apps: 
  forms814:
    command: bin/forms814
    extensions: [gnome]
  